name: Test compilation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ build ]

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Try to restore opam cache
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: opam-${{ hashFiles('opam') }}

      - name: Install OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.12.0

      - name: Install Coq and Iris
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam install . --deps-only -y

      - name: Build
        run: opam exec -- make ci -j $(nproc)

      - name: Build docs
        run: opam exec -- make html

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          destination_dir: dev
